modLoader = "javafml"
loaderVersion = "[39,)"
license = "Apache 2.0"

[[mods]]
modId = "morexfood"
version = "${file.jarVersion}"
displayName = "More XFood"
updateJSONURL = "https://assets.melanx.de/updates/morexfood.json"
authors = "MelanX"
description = '''
This is my first mod. It's for learning how to build a mod but it's a christmas present for my girlfriend, too. It adds her favourite food and a few ingredients for this.
'''

[[dependencies.morexfood]]
    modId = "forge"
    mandatory = true
    versionRange = "[39,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.morexfood]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.1, 1.19)"
    ordering = "NONE"
    side = "BOTH"